# Generated by Django 3.1.3 on 2020-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0002_messagesconfiguration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesconfiguration',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='IsActive', null=True),
        ),
    ]
