# Generated by Django 3.1.4 on 2021-02-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0002_errornumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslist',
            name='departure_date',
            field=models.CharField(blank=True, db_column='DepartureDate', max_length=20, null=True),
        ),
    ]
