# Generated by Django 3.1.3 on 2020-12-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0003_auto_20201128_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageslist',
            name='departure_date',
            field=models.CharField(blank=True, db_column='DepartureDate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='messageslist',
            name='price',
            field=models.CharField(blank=True, db_column='Price', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messagesconfiguration',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='IsActive', default=0, null=True),
        ),
    ]
