# Generated by Django 3.1.3 on 2020-12-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0004_auto_20201201_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageslist',
            name='price',
        ),
        migrations.AddField(
            model_name='messageslist',
            name='amount',
            field=models.CharField(blank=True, db_column='Amount', max_length=20, null=True),
        ),
    ]
