# Generated by Django 3.1.3 on 2020-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0006_auto_20201201_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslist',
            name='amount',
            field=models.FloatField(blank=True, db_column='Amount', max_length=20, null=True),
        ),
    ]
