# Generated by Django 3.1.4 on 2021-01-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0008_messageslist_charge_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageslist',
            name='charge_date',
        ),
    ]
