# Generated by Django 3.1.4 on 2021-01-21 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagesconf', '0009_remove_messageslist_charge_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorNumber',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('id_error_number', models.AutoField(db_column='IdErrorNumber', primary_key=True, serialize=False)),
                ('creation_user', models.ForeignKey(db_column='CreationUser', on_delete=django.db.models.deletion.DO_NOTHING, related_name='en_creation_user', to=settings.AUTH_USER_MODEL)),
                ('message_list', models.ForeignKey(db_column='MessageList', on_delete=django.db.models.deletion.DO_NOTHING, to='messagesconf.messageslist')),
                ('modification_user', models.ForeignKey(db_column='ModificationUser', on_delete=django.db.models.deletion.DO_NOTHING, related_name='en_modification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
