# Generated by Django 3.1.3 on 2020-11-28 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messagesconf', '0002_auto_20201127_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesconfiguration',
            name='text',
            field=models.TextField(blank=True, db_column='Text', null=True),
        ),
        migrations.CreateModel(
            name='MessagesCampaign',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('id_message_campaign', models.AutoField(db_column='IdMessageCampaign', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('creation_user', models.ForeignKey(db_column='CreationUser', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mca_creation_user', to=settings.AUTH_USER_MODEL)),
                ('id_message_configuration', models.ForeignKey(db_column='IdMessageConfiguration', on_delete=django.db.models.deletion.DO_NOTHING, to='messagesconf.messagesconfiguration')),
                ('modification_user', models.ForeignKey(db_column='ModificationUser', on_delete=django.db.models.deletion.DO_NOTHING, related_name='mca_modification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
