# Generated by Django 3.1.3 on 2020-11-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0003_auto_20201128_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesconfiguration',
            name='name',
            field=models.TextField(blank=True, db_column='Name', null=True),
        ),
        migrations.DeleteModel(
            name='MessagesCampaign',
        ),
    ]
