# Generated by Django 3.1.3 on 2020-11-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconf', '0004_auto_20201128_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesconfiguration',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=50, null=True),
        ),
    ]
